import numpy as np
import matplotlib.pylab as plt

dt0 = np.genfromtxt('data.txt', skip_header=(0), usecols =(0))
x_dt0 = np.genfromtxt('data.txt', skip_header=(0), usecols =(1))
vx_dt0 = np.genfromtxt('data.txt', skip_header=(0), usecols =(2))
y_dt0 = np.genfromtxt('data.txt', skip_header=(0), usecols =(3))
vy_dt0 = np.genfromtxt('data.txt', skip_header=(0), usecols =(4))

dt1 = np.genfromtxt('data.txt', skip_header=(0), usecols =(5))
x_dt1 = np.genfromtxt('data.txt', skip_header=(0), usecols =(6))
vx_dt1 = np.genfromtxt('data.txt', skip_header=(0), usecols =(7))
y_dt1 = np.genfromtxt('data.txt', skip_header=(0), usecols =(8))
vy_dt1 = np.genfromtxt('data.txt', skip_header=(0), usecols =(9))

dt2 = np.genfromtxt('data.txt', skip_header=(0), usecols =(10))
x_dt2= np.genfromtxt('data.txt', skip_header=(0), usecols =(11))
vx_dt2 = np.genfromtxt('data.txt', skip_header=(0), usecols =(12))
y_dt2 = np.genfromtxt('data.txt', skip_header=(0), usecols =(13))
vy_dt2 = np.genfromtxt('data.txt', skip_header=(0), usecols =(14))

fig0 = plt.figure(figsize=(20,4))
ax0 = fig0.add_subplot(131)
ax0.plot(x_dt0, y_dt0, 'navy', label = ('Posición'))
ax0.set_xlabel('$Posición$ $x$ [UA]', size = 15)
ax0.set_ylabel('$Posición$ $y$ [UA]', size = 15)
ax0.set_title('RugenKutta: dt = 0.1 - 2000 Orbitas')
ax0.legend()

ax1 = fig0.add_subplot(132)
ax1.plot(x_dt1, y_dt1, 'navy', label = ('Posición'))
ax1.set_xlabel('$Posición$ $x$ [UA]', size = 15)
ax1.set_ylabel('$Posición$ $y$ [UA]', size = 15)
ax1.set_title('RugenKutta: dt = 0.01 - 200 Orbitas')
ax1.legend()

ax2 = fig0.add_subplot(133)
ax2.plot(x_dt2, y_dt2, 'navy', label = ('Posición'))
ax2.set_xlabel('$Posición$ $x$ [UA]', size = 15)
ax2.set_ylabel('$Posición$ $y$ [UA]', size = 15)
ax2.set_title('RugenKutta: dt = 0.001 - 20 Orbitas')
ax2.legend()

fig1 = plt.figure(figsize=(20,4))
ax0 = fig1.add_subplot(131)
ax0.plot(vx_dt0, vy_dt0, 'firebrick', label = ('Velocidad'))
ax0.set_xlabel('$Velocidad$ $x$ [UA/yrs$^2$]', size = 15)
ax0.set_ylabel('$Velocidad$ $y$ [UA/yrs$^2$]', size = 15)
ax0.set_title('RugenKutta: dt = 0.1 - 2000 Orbitas')
ax0.legend()

ax1 = fig1.add_subplot(132)
ax1.plot(vx_dt1, vy_dt1, 'firebrick', label = ('Velocidad'))
ax1.set_xlabel('$Velocidad$ $x$ [UA/yrs$^2$]', size = 15)
ax1.set_ylabel('$Velocidad$ $y$ [UA/yrs$^2$]', size = 15)
ax1.set_title('RugenKutta: dt = 0.01 - 200 Orbitas')
ax1.legend()

ax2 = fig1.add_subplot(133)
ax2.plot(vx_dt2, vy_dt2, 'firebrick', label = ('Velocidad'))
ax2.set_xlabel('$Velocidad$ $x$ [UA/yrs$^2$]', size = 15)
ax2.set_ylabel('$Velocidad$ $y$ [UA/yrs$^2$]', size = 15)
ax2.set_title('RugenKutta: dt = 0.001 - 20 Orbitas')
ax2.legend()
